language: python
python:
  - "3.6"
before_script:
  - pip install -r requirements.txt
  - wget --quiet -O http://nlp.stanford.edu/software/conll_2018/en_ewt_models.zip ./models/en_ewt_models.zip
script:
  - python -m pytest tests
  - python setup.py sdist
cache: pip
notifications:
  email: false
