language: python
python:
  - "3.6"
before_install:
  - pip install -U pip
install:
  - pip install -r requirements.txt --progress-bar off
  - wget --quiet -O http://nlp.stanford.edu/software/conll_2018/en_ewt_models.zip ./models/en_ewt_models.zip
script:
  - python -m pytest tests
  - python setup.py sdist
cache: pip
notifications:
  email: false
